Implement training and cross val
isaac-project/isaac-ml-service pull request #10
Opened 2021-02-18 21:16 UTC by janniss91

Here is the new implementation of the ```do_training``` method and the trainFromAnswers with actual feature extraction.

1. Unfortunately, due to the renewed setup of the BOW for every cross validation run, I had to write a new training method for the trainFromAnswers endpoint.
2. The training from CAS now also has cross validation implemented. Unfortunately I had to skip one of the tests now because when using cross validation at least two training instances are required. The CAS instance apparently only has one training instance stored. Maybe we can find a solution for this in the future. Otherwise the function should work.
3. Training now returns a dictionary with training metrics (Accuracy, F1, Cohen's Kappa) for the model with all three of the metrics respectively. The metrics are also provided per output class. The dictionary is also written to a JSON file, which is stored inside the repository in the directory `model_metrics`.
4. The model is stored as ONNX as before. I have refactored the ONNX model storing out of the training functions to reuse it and to make the functions a bit shorter.

2021-02-18 21:18 UTC, janniss91 commented
The tests seem to fail because of a wrong pointer to the submodule.  
I'll look into this.

2021-02-19 15:43 UTC, janniss91 commented
Sorry for pushing broken code in the first place.
The tests ran on my machine, that's why I didn't realize the two problems.

The problems were:
1. I hadn't pushed the changes to the features repo so it couldn't find the right commit.
2. The `model_metrics` directory wasn't pushed because it is empty at the moment.

2021-02-24 16:45 UTC, ramonziai requested changes
Looking good overall! One smaller thing occurred to me: could you use StratifiedKFold instead of KFold so we can take the label distribution into account?

2021-02-24 17:08 UTC, janniss91 commented
Sure, I'll see how to implement it.

2021-02-25 14:52 UTC, janniss91 commented
I have changed from Kfold CV to Stratified Kfold CV now.

2021-02-26 11:02 UTC, ramonziai approved these changes

2021-02-26 11:03 UTC, merged